### ISSUE TITLE
Disabling the "show quantities inline" option only removes (some) units and not the value

### ISSUE THREAD

**Issue by RichSteele** [deathau/cooklang-obsidian#5]
I'm not sure the intention of the "show quantities inline" option: when disabled, the quantities are shown but some display without the units. For example:

```
Crack the @eggs{3} into a blender, then add the @flour{125%g}, @milk{250%ml} and @sea salt{1%pinch}, and blitz until smooth.
```

![image](https://user-images.githubusercontent.com/2944434/141653847-a74f3efc-8186-440f-ac24-892ccfd6dce3.png)

Notice that the "g" is missing from the flour measurement and the other units are showing. Enabling this option shows the "g" (and all of the others as well).

**Comment by deathau** [comment]
Yep, I see what I did wrong.
My code puts all the measurements in by default, and if the inline quantities setting is disabled, it removes them all. But the code I was using only removed the _first_ quantity and the _first_ unit, instead of _all_ the quantities and units 😖 
Will fix in the next version

**Comment by RichSteele** [comment]
Confirmed this resolves the issue, thank you.
